import { Haversine } from './Haversine';
import { getNodeCoords } from './geoCoords';

export interface GeoNode {
  id: string;
  name: string;
  type: 'CITY' | 'AIRPORT' | 'STATION';
  lat: number;
  lng: number;
  cityId?: string;
  irctcCode?: string;
}

export const GEO_DB: GeoNode[] = [
  { id: 'city_patna', name: 'Patna', type: 'CITY', lat: 25.5941, lng: 85.1376 },
  { id: 'city_kolkata', name: 'Kolkata', type: 'CITY', lat: 22.5726, lng: 88.3639 },
  { id: 'city_bangalore', name: 'Bangalore', type: 'CITY', lat: 12.9716, lng: 77.5946 },
  { id: 'city_delhi', name: 'Delhi', type: 'CITY', lat: 28.7041, lng: 77.1025 },
  { id: 'city_mumbai', name: 'Mumbai', type: 'CITY', lat: 19.076, lng: 72.8777 },
  { id: 'city_chennai', name: 'Chennai', type: 'CITY', lat: 13.0827, lng: 80.2707 },
  { id: 'city_hyderabad', name: 'Hyderabad', type: 'CITY', lat: 17.385, lng: 78.4867 },
  { id: 'city_ahmedabad', name: 'Ahmedabad', type: 'CITY', lat: 23.0225, lng: 72.5714 },
  { id: 'city_jaipur', name: 'Jaipur', type: 'CITY', lat: 26.9124, lng: 75.7873 },
  { id: 'city_lucknow', name: 'Lucknow', type: 'CITY', lat: 26.8467, lng: 80.9462 },
  { id: 'city_chandigarh', name: 'Chandigarh', type: 'CITY', lat: 30.7333, lng: 76.7794 },
  { id: 'city_guwahati', name: 'Guwahati', type: 'CITY', lat: 26.1445, lng: 91.7362 },
  { id: 'apt_patna', name: 'Jay Prakash Narayan Airport', type: 'AIRPORT', lat: 25.5913, lng: 85.0872, cityId: 'city_patna' },
  { id: 'stn_patna', name: 'Patna Junction', type: 'STATION', lat: 25.5913, lng: 85.0872, cityId: 'city_patna', irctcCode: 'PNBE' },
  { id: 'apt_kolkata', name: 'Netaji Subhas Chandra Bose International Airport', type: 'AIRPORT', lat: 22.652, lng: 88.4463, cityId: 'city_kolkata' },
  { id: 'stn_kolkata', name: 'Howrah Junction', type: 'STATION', lat: 22.5833, lng: 88.3433, cityId: 'city_kolkata', irctcCode: 'HWH' },
  { id: 'apt_bangalore', name: 'Kempegowda International Airport', type: 'AIRPORT', lat: 13.1986, lng: 77.7066, cityId: 'city_bangalore' },
  { id: 'stn_bangalore', name: 'Krantivira Sangolli Rayanna (Bengaluru)', type: 'STATION', lat: 12.9784, lng: 77.5684, cityId: 'city_bangalore', irctcCode: 'SBC' },
  { id: 'apt_delhi', name: 'Indira Gandhi Int. Airport', type: 'AIRPORT', lat: 28.5562, lng: 77.1, cityId: 'city_delhi' },
  { id: 'stn_delhi', name: 'New Delhi', type: 'STATION', lat: 28.6429, lng: 77.2191, cityId: 'city_delhi', irctcCode: 'NDLS' },
  { id: 'apt_mumbai', name: 'Chhatrapati Shivaji Maharaj International Airport', type: 'AIRPORT', lat: 19.0905, lng: 72.8628, cityId: 'city_mumbai' },
  { id: 'stn_mumbai', name: 'Chhatrapati Shivaji Maharaj Terminus', type: 'STATION', lat: 18.9398, lng: 72.8354, cityId: 'city_mumbai', irctcCode: 'CSMT' },
  { id: 'apt_chennai', name: 'Chennai International Airport', type: 'AIRPORT', lat: 12.9941, lng: 80.1709, cityId: 'city_chennai' },
  { id: 'stn_chennai', name: 'Chennai Central', type: 'STATION', lat: 13.0827, lng: 80.2755, cityId: 'city_chennai', irctcCode: 'MAS' },
  { id: 'apt_hyderabad', name: 'Rajiv Gandhi International Airport', type: 'AIRPORT', lat: 17.2403, lng: 78.4294, cityId: 'city_hyderabad' },
  { id: 'stn_hyderabad', name: 'Secunderabad Junction', type: 'STATION', lat: 17.4337, lng: 78.5016, cityId: 'city_hyderabad', irctcCode: 'SC' },
  { id: 'apt_ahmedabad', name: 'Sardar Vallabhbhai Patel Int. Airport', type: 'AIRPORT', lat: 23.0734, lng: 72.6266, cityId: 'city_ahmedabad' },
  { id: 'apt_jaipur', name: 'Jaipur Int. Airport', type: 'AIRPORT', lat: 26.8242, lng: 75.8016, cityId: 'city_jaipur' },
  { id: 'apt_lucknow', name: 'Chaudhary Charan Singh Airport', type: 'AIRPORT', lat: 26.7606, lng: 80.8893, cityId: 'city_lucknow' },
  { id: 'apt_chandigarh', name: 'Chandigarh Airport', type: 'AIRPORT', lat: 30.6735, lng: 76.7885, cityId: 'city_chandigarh' },
  { id: 'apt_guwahati', name: 'Lokpriya Gopinath Bordoloi Airport', type: 'AIRPORT', lat: 26.1061, lng: 91.5859, cityId: 'city_guwahati' },
  { id: 'stn_lucknow', name: 'Lucknow Junction', type: 'STATION', lat: 26.8306, lng: 80.9205, cityId: 'city_lucknow' },
  { id: 'stn_chandigarh', name: 'Chandigarh Junction', type: 'STATION', lat: 30.7046, lng: 76.8016, cityId: 'city_chandigarh' },
  { id: 'stn_guwahati', name: 'Guwahati Station', type: 'STATION', lat: 26.1843, lng: 91.7483, cityId: 'city_guwahati' },
  { id: 'city_agra', name: 'Agra', type: 'CITY', lat: 27.1767, lng: 78.0081 },
  { id: 'apt_agra', name: 'Agra Airport', type: 'AIRPORT', lat: 27.1767, lng: 78.0081, cityId: 'city_agra' },
  { id: 'stn_gaya', name: 'Gaya Junction', type: 'STATION', lat: 24.7964, lng: 84.9961, cityId: 'city_gaya', irctcCode: 'GAYA' },
  { id: 'city_varanasi', name: 'Varanasi', type: 'CITY', lat: 25.3176, lng: 82.9739 },
  { id: 'apt_varanasi', name: 'Lal Bahadur Shastri Airport', type: 'AIRPORT', lat: 25.4523, lng: 82.8593, cityId: 'city_varanasi' },
  { id: 'stn_varanasi', name: 'Varanasi Junction', type: 'STATION', lat: 25.3345, lng: 82.9778, cityId: 'city_varanasi', irctcCode: 'BSB' },
  { id: 'city_kanpur', name: 'Kanpur', type: 'CITY', lat: 26.4499, lng: 80.3319 },
  { id: 'apt_kanpur', name: 'Kanpur Airport', type: 'AIRPORT', lat: 26.4499, lng: 80.3319, cityId: 'city_kanpur' },
  { id: 'stn_kanpur', name: 'Kanpur Central', type: 'STATION', lat: 26.4499, lng: 80.3319, cityId: 'city_kanpur' },
  { id: 'city_nagpur', name: 'Nagpur', type: 'CITY', lat: 21.1458, lng: 79.0882 },
  { id: 'apt_nagpur', name: 'Dr. Babasaheb Ambedkar Int. Airport', type: 'AIRPORT', lat: 21.1458, lng: 79.0882, cityId: 'city_nagpur' },
  { id: 'stn_nagpur', name: 'Nagpur Junction', type: 'STATION', lat: 21.1458, lng: 79.0882, cityId: 'city_nagpur' },
  { id: 'city_visakhapatnam', name: 'Visakhapatnam', type: 'CITY', lat: 17.6868, lng: 83.2185 },
  { id: 'apt_visakhapatnam', name: 'Visakhapatnam Airport', type: 'AIRPORT', lat: 17.6868, lng: 83.2185, cityId: 'city_visakhapatnam' },
  { id: 'stn_visakhapatnam', name: 'Visakhapatnam Junction', type: 'STATION', lat: 17.6868, lng: 83.2185, cityId: 'city_visakhapatnam' },
  { id: 'city_thiruvananthapuram', name: 'Thiruvananthapuram', type: 'CITY', lat: 8.5241, lng: 76.9366 },
  { id: 'apt_thiruvananthapuram', name: 'Trivandrum Int. Airport', type: 'AIRPORT', lat: 8.5241, lng: 76.9366, cityId: 'city_thiruvananthapuram' },
  { id: 'stn_thiruvananthapuram', name: 'Thiruvananthapuram Central', type: 'STATION', lat: 8.5241, lng: 76.9366, cityId: 'city_thiruvananthapuram' },
  { id: 'city_madurai', name: 'Madurai', type: 'CITY', lat: 9.9252, lng: 78.1198 },
  { id: 'apt_madurai', name: 'Madurai Airport', type: 'AIRPORT', lat: 9.9252, lng: 78.1198, cityId: 'city_madurai' },
  { id: 'stn_madurai', name: 'Madurai Junction', type: 'STATION', lat: 9.9252, lng: 78.1198, cityId: 'city_madurai' },
  { id: 'city_coimbatore', name: 'Coimbatore', type: 'CITY', lat: 11.0168, lng: 76.9558 },
  { id: 'apt_coimbatore', name: 'Coimbatore Int. Airport', type: 'AIRPORT', lat: 11.0168, lng: 76.9558, cityId: 'city_coimbatore' },
  { id: 'stn_coimbatore', name: 'Coimbatore Junction', type: 'STATION', lat: 11.0168, lng: 76.9558, cityId: 'city_coimbatore' },
  { id: 'city_jodhpur', name: 'Jodhpur', type: 'CITY', lat: 26.2389, lng: 73.0243 },
  { id: 'apt_jodhpur', name: 'Jodhpur Airport', type: 'AIRPORT', lat: 26.2389, lng: 73.0243, cityId: 'city_jodhpur' },
  { id: 'stn_jodhpur', name: 'Jodhpur Junction', type: 'STATION', lat: 26.2389, lng: 73.0243, cityId: 'city_jodhpur' },
  { id: 'city_udaipur', name: 'Udaipur', type: 'CITY', lat: 24.5854, lng: 73.7125 },
  { id: 'apt_udaipur', name: 'Maharana Pratap Airport', type: 'AIRPORT', lat: 24.5854, lng: 73.7125, cityId: 'city_udaipur' },
  { id: 'stn_udaipur', name: 'Udaipur City', type: 'STATION', lat: 24.5854, lng: 73.7125, cityId: 'city_udaipur' },
  { id: 'city_amritsar', name: 'Amritsar', type: 'CITY', lat: 31.634, lng: 74.8723 },
  { id: 'apt_amritsar', name: 'Sri Guru Ram Dass Jee Int. Airport', type: 'AIRPORT', lat: 31.634, lng: 74.8723, cityId: 'city_amritsar' },
  { id: 'stn_amritsar', name: 'Amritsar Junction', type: 'STATION', lat: 31.634, lng: 74.8723, cityId: 'city_amritsar' },
  { id: 'city_dehradun', name: 'Dehradun', type: 'CITY', lat: 30.3165, lng: 78.0322 },
  { id: 'apt_dehradun', name: 'Jolly Grant Airport', type: 'AIRPORT', lat: 30.3165, lng: 78.0322, cityId: 'city_dehradun' },
  { id: 'stn_dehradun', name: 'Dehradun Station', type: 'STATION', lat: 30.3165, lng: 78.0322, cityId: 'city_dehradun' },
  { id: 'city_ranchi', name: 'Ranchi', type: 'CITY', lat: 23.3441, lng: 85.3096 },
  { id: 'apt_ranchi', name: 'Birsa Munda Airport', type: 'AIRPORT', lat: 23.3441, lng: 85.3096, cityId: 'city_ranchi' },
  { id: 'stn_ranchi', name: 'Ranchi Junction', type: 'STATION', lat: 23.3421, lng: 85.3218, cityId: 'city_ranchi', irctcCode: 'RNC' },
  { id: 'city_raipur', name: 'Raipur', type: 'CITY', lat: 21.2514, lng: 81.6296 },
  { id: 'apt_raipur', name: 'Swami Vivekananda Airport', type: 'AIRPORT', lat: 21.2514, lng: 81.6296, cityId: 'city_raipur' },
  { id: 'stn_raipur', name: 'Raipur Junction', type: 'STATION', lat: 21.2514, lng: 81.6296, cityId: 'city_raipur' },
  { id: 'city_mysore', name: 'Mysore', type: 'CITY', lat: 12.2958, lng: 76.6394 },
  { id: 'apt_mysore', name: 'Mysore Airport', type: 'AIRPORT', lat: 12.2958, lng: 76.6394, cityId: 'city_mysore' },
  { id: 'stn_mysore', name: 'Mysuru Junction', type: 'STATION', lat: 12.2958, lng: 76.6394, cityId: 'city_mysore' },
  { id: 'city_mangalore', name: 'Mangalore', type: 'CITY', lat: 12.9141, lng: 74.856 },
  { id: 'apt_mangalore', name: 'Mangaluru Int. Airport', type: 'AIRPORT', lat: 12.9141, lng: 74.856, cityId: 'city_mangalore' },
  { id: 'stn_mangalore', name: 'Mangaluru Central', type: 'STATION', lat: 12.9141, lng: 74.856, cityId: 'city_mangalore' },
  { id: 'city_vijayawada', name: 'Vijayawada', type: 'CITY', lat: 16.5062, lng: 80.648 },
  { id: 'apt_vijayawada', name: 'Vijayawada Airport', type: 'AIRPORT', lat: 16.5062, lng: 80.648, cityId: 'city_vijayawada' },
  { id: 'stn_vijayawada', name: 'Vijayawada Junction', type: 'STATION', lat: 16.5062, lng: 80.648, cityId: 'city_vijayawada' },
  { id: 'city_tirupati', name: 'Tirupati', type: 'CITY', lat: 13.6288, lng: 79.4192 },
  { id: 'apt_tirupati', name: 'Tirupati Airport', type: 'AIRPORT', lat: 13.6288, lng: 79.4192, cityId: 'city_tirupati' },
  { id: 'stn_tirupati', name: 'Tirupati Main', type: 'STATION', lat: 13.6288, lng: 79.4192, cityId: 'city_tirupati' },
  { id: 'city_vadodara', name: 'Vadodara', type: 'CITY', lat: 22.3072, lng: 73.1812 },
  { id: 'apt_vadodara', name: 'Vadodara Airport', type: 'AIRPORT', lat: 22.3072, lng: 73.1812, cityId: 'city_vadodara' },
  { id: 'stn_vadodara', name: 'Vadodara Junction', type: 'STATION', lat: 22.3072, lng: 73.1812, cityId: 'city_vadodara' },
  { id: 'city_rajkot', name: 'Rajkot', type: 'CITY', lat: 22.3039, lng: 70.8022 },
  { id: 'apt_rajkot', name: 'Rajkot Airport', type: 'AIRPORT', lat: 22.3039, lng: 70.8022, cityId: 'city_rajkot' },
  { id: 'stn_rajkot', name: 'Rajkot Junction', type: 'STATION', lat: 22.3039, lng: 70.8022, cityId: 'city_rajkot' },
  { id: 'city_aurangabad', name: 'Aurangabad', type: 'CITY', lat: 19.8762, lng: 75.3433 },
  { id: 'apt_aurangabad', name: 'Aurangabad Airport', type: 'AIRPORT', lat: 19.8762, lng: 75.3433, cityId: 'city_aurangabad' },
  { id: 'stn_aurangabad', name: 'Aurangabad Station', type: 'STATION', lat: 19.8762, lng: 75.3433, cityId: 'city_aurangabad' },
  { id: 'city_nashik', name: 'Nashik', type: 'CITY', lat: 19.9975, lng: 73.7898 },
  { id: 'apt_nashik', name: 'Nashik Airport', type: 'AIRPORT', lat: 19.9975, lng: 73.7898, cityId: 'city_nashik' },
  { id: 'stn_nashik', name: 'Nashik Road', type: 'STATION', lat: 19.9975, lng: 73.7898, cityId: 'city_nashik' },
  { id: 'city_gwalior', name: 'Gwalior', type: 'CITY', lat: 26.2183, lng: 78.1828 },
  { id: 'apt_gwalior', name: 'Gwalior Airport', type: 'AIRPORT', lat: 26.2183, lng: 78.1828, cityId: 'city_gwalior' },
  { id: 'stn_gwalior', name: 'Gwalior Junction', type: 'STATION', lat: 26.2183, lng: 78.1828, cityId: 'city_gwalior' },
  { id: 'city_jabalpur', name: 'Jabalpur', type: 'CITY', lat: 23.1815, lng: 79.9864 },
  { id: 'apt_jabalpur', name: 'Jabalpur Airport', type: 'AIRPORT', lat: 23.1815, lng: 79.9864, cityId: 'city_jabalpur' },
  { id: 'stn_jabalpur', name: 'Jabalpur Junction', type: 'STATION', lat: 23.1815, lng: 79.9864, cityId: 'city_jabalpur' },
  { id: 'city_jamshedpur', name: 'Jamshedpur', type: 'CITY', lat: 22.8046, lng: 86.2029 },
  { id: 'apt_jamshedpur', name: 'Sonari Airport', type: 'AIRPORT', lat: 22.8046, lng: 86.2029, cityId: 'city_jamshedpur' },
  { id: 'stn_jamshedpur', name: 'Tatanagar Junction', type: 'STATION', lat: 22.8046, lng: 86.2029, cityId: 'city_jamshedpur' },
  { id: 'city_siliguri', name: 'Siliguri', type: 'CITY', lat: 26.7271, lng: 88.3953 },
  { id: 'apt_siliguri', name: 'Bagdogra Airport', type: 'AIRPORT', lat: 26.7271, lng: 88.3953, cityId: 'city_siliguri' },
  { id: 'stn_siliguri', name: 'New Jalpaiguri', type: 'STATION', lat: 26.7271, lng: 88.3953, cityId: 'city_siliguri' },
  { id: 'city_gorakhpur', name: 'Gorakhpur', type: 'CITY', lat: 26.7606, lng: 83.3732 },
  { id: 'apt_gorakhpur', name: 'Gorakhpur Airport', type: 'AIRPORT', lat: 26.7606, lng: 83.3732, cityId: 'city_gorakhpur' },
  { id: 'stn_gorakhpur', name: 'Gorakhpur Junction', type: 'STATION', lat: 26.7606, lng: 83.3732, cityId: 'city_gorakhpur' },
  { id: 'city_prayagraj', name: 'Prayagraj', type: 'CITY', lat: 25.4358, lng: 81.8463 },
  { id: 'apt_prayagraj', name: 'Prayagraj Airport', type: 'AIRPORT', lat: 25.4358, lng: 81.8463, cityId: 'city_prayagraj' },
  { id: 'stn_prayagraj', name: 'Prayagraj Junction', type: 'STATION', lat: 25.4358, lng: 81.8463, cityId: 'city_prayagraj' },
  { id: 'city_jammu', name: 'Jammu', type: 'CITY', lat: 32.7266, lng: 74.857 },
  { id: 'apt_jammu', name: 'Jammu Airport', type: 'AIRPORT', lat: 32.7266, lng: 74.857, cityId: 'city_jammu' },
  { id: 'stn_jammu', name: 'Jammu Tawi', type: 'STATION', lat: 32.7266, lng: 74.857, cityId: 'city_jammu' },
  { id: 'city_srinagar', name: 'Srinagar', type: 'CITY', lat: 34.0837, lng: 74.7973 },
  { id: 'apt_srinagar', name: 'Sheikh ul-Alam Int. Airport', type: 'AIRPORT', lat: 34.0837, lng: 74.7973, cityId: 'city_srinagar' },
  { id: 'stn_srinagar', name: 'Srinagar Station', type: 'STATION', lat: 34.0837, lng: 74.7973, cityId: 'city_srinagar' },
  { id: 'city_leh', name: 'Leh', type: 'CITY', lat: 34.1526, lng: 77.5771 },
  { id: 'apt_leh', name: 'Kushok Bakula Rimpochee Airport', type: 'AIRPORT', lat: 34.1526, lng: 77.5771, cityId: 'city_leh' },
  { id: 'city_shillong', name: 'Shillong', type: 'CITY', lat: 25.5788, lng: 91.8933 },
  { id: 'apt_shillong', name: 'Shillong Airport', type: 'AIRPORT', lat: 25.5788, lng: 91.8933, cityId: 'city_shillong' },
  { id: 'stn_shillong', name: 'Guwahati Station', type: 'STATION', lat: 25.5788, lng: 91.8933, cityId: 'city_shillong' },
  { id: 'city_agartala', name: 'Agartala', type: 'CITY', lat: 23.8315, lng: 91.2868 },
  { id: 'apt_agartala', name: 'Maharaja Bir Bikram Airport', type: 'AIRPORT', lat: 23.8315, lng: 91.2868, cityId: 'city_agartala' },
  { id: 'stn_agartala', name: 'Agartala Station', type: 'STATION', lat: 23.8315, lng: 91.2868, cityId: 'city_agartala' },
  { id: 'city_dibrugarh', name: 'Dibrugarh', type: 'CITY', lat: 27.4728, lng: 94.912 },
  { id: 'apt_dibrugarh', name: 'Dibrugarh Airport', type: 'AIRPORT', lat: 27.4728, lng: 94.912, cityId: 'city_dibrugarh' },
  { id: 'stn_dibrugarh', name: 'Dibrugarh Town', type: 'STATION', lat: 27.4728, lng: 94.912, cityId: 'city_dibrugarh' },
  { id: 'city_silchar', name: 'Silchar', type: 'CITY', lat: 24.8333, lng: 92.7789 },
  { id: 'apt_silchar', name: 'Silchar Airport', type: 'AIRPORT', lat: 24.8333, lng: 92.7789, cityId: 'city_silchar' },
  { id: 'stn_silchar', name: 'Silchar Station', type: 'STATION', lat: 24.8333, lng: 92.7789, cityId: 'city_silchar' },
  { id: 'city_pune', name: 'Pune', type: 'CITY', lat: 18.5204, lng: 73.8567 },
  { id: 'apt_pune', name: 'Pune Airport', type: 'AIRPORT', lat: 18.5204, lng: 73.8567, cityId: 'city_pune' },
  { id: 'stn_pune', name: 'Pune Junction', type: 'STATION', lat: 18.5204, lng: 73.8567, cityId: 'city_pune' },
  { id: 'city_ludhiana', name: 'Ludhiana', type: 'CITY', lat: 30.901, lng: 75.8573 },
  { id: 'apt_ludhiana', name: 'Sahnewal Airport', type: 'AIRPORT', lat: 30.901, lng: 75.8573, cityId: 'city_ludhiana' },
  { id: 'stn_ludhiana', name: 'Ludhiana Junction', type: 'STATION', lat: 30.901, lng: 75.8573, cityId: 'city_ludhiana' },
  { id: 'city_patiala', name: 'Patiala', type: 'CITY', lat: 30.3398, lng: 76.3869 },
  { id: 'stn_patiala', name: 'Patiala Station', type: 'STATION', lat: 30.3398, lng: 76.3869, cityId: 'city_patiala' },
  { id: 'city_kozhikode', name: 'Kozhikode', type: 'CITY', lat: 11.2588, lng: 75.7804 },
  { id: 'apt_kozhikode', name: 'Calicut Int. Airport', type: 'AIRPORT', lat: 11.2588, lng: 75.7804, cityId: 'city_kozhikode' },
  { id: 'stn_kozhikode', name: 'Kozhikode Main', type: 'STATION', lat: 11.2588, lng: 75.7804, cityId: 'city_kozhikode' },
  { id: 'city_kochi', name: 'Kochi', type: 'CITY', lat: 9.9312, lng: 76.2673 },
  { id: 'apt_kochi', name: 'Cochin Int. Airport', type: 'AIRPORT', lat: 9.9312, lng: 76.2673, cityId: 'city_kochi' },
  { id: 'stn_kochi', name: 'Ernakulam Junction', type: 'STATION', lat: 9.9312, lng: 76.2673, cityId: 'city_kochi' },
  { id: 'city_tiruchirappalli', name: 'Tiruchirappalli', type: 'CITY', lat: 10.7905, lng: 78.7047 },
  { id: 'apt_tiruchirappalli', name: 'Tiruchirappalli Int. Airport', type: 'AIRPORT', lat: 10.7905, lng: 78.7047, cityId: 'city_tiruchirappalli' },
  { id: 'stn_tiruchirappalli', name: 'Tiruchirappalli Junction', type: 'STATION', lat: 10.7905, lng: 78.7047, cityId: 'city_tiruchirappalli' },
  { id: 'city_bhubaneswar', name: 'Bhubaneswar', type: 'CITY', lat: 20.2961, lng: 85.8245 },
  { id: 'apt_bhubaneswar', name: 'Biju Patnaik Airport', type: 'AIRPORT', lat: 20.2961, lng: 85.8245, cityId: 'city_bhubaneswar' },
  { id: 'stn_bhubaneswar', name: 'Bhubaneswar Station', type: 'STATION', lat: 20.2961, lng: 85.8245, cityId: 'city_bhubaneswar' },
  { id: 'city_rourkela', name: 'Rourkela', type: 'CITY', lat: 22.2604, lng: 84.8536 },
  { id: 'apt_rourkela', name: 'Rourkela Airport', type: 'AIRPORT', lat: 22.2604, lng: 84.8536, cityId: 'city_rourkela' },
  { id: 'stn_rourkela', name: 'Rourkela Junction', type: 'STATION', lat: 22.2604, lng: 84.8536, cityId: 'city_rourkela' },
  { id: 'city_bhopal', name: 'Bhopal', type: 'CITY', lat: 23.2599, lng: 77.4126 },
  { id: 'apt_bhopal', name: 'Raja Bhoj Airport', type: 'AIRPORT', lat: 23.2599, lng: 77.4126, cityId: 'city_bhopal' },
  { id: 'stn_bhopal', name: 'Bhopal Junction', type: 'STATION', lat: 23.2599, lng: 77.4126, cityId: 'city_bhopal' },
  { id: 'city_indore', name: 'Indore', type: 'CITY', lat: 22.7196, lng: 75.8577 },
  { id: 'apt_indore', name: 'Devi Ahilya Bai Holkar Airport', type: 'AIRPORT', lat: 22.7196, lng: 75.8577, cityId: 'city_indore' },
  { id: 'stn_indore', name: 'Indore Junction', type: 'STATION', lat: 22.7196, lng: 75.8577, cityId: 'city_indore' },
  { id: 'city_ujjain', name: 'Ujjain', type: 'CITY', lat: 23.1765, lng: 75.7885 },
  { id: 'stn_ujjain', name: 'Ujjain Junction', type: 'STATION', lat: 23.1765, lng: 75.7885, cityId: 'city_ujjain' },
  { id: 'city_gaya', name: 'Gaya', type: 'CITY', lat: 24.7805, lng: 85.0158 },
  { id: 'apt_gaya', name: 'Gaya Airport', type: 'AIRPORT', lat: 24.7443, lng: 84.9512, cityId: 'city_gaya' },
  { id: 'city_bhagalpur', name: 'Bhagalpur', type: 'CITY', lat: 25.2425, lng: 86.9842 },
  { id: 'stn_bhagalpur', name: 'Bhagalpur Junction', type: 'STATION', lat: 25.2425, lng: 86.9842, cityId: 'city_bhagalpur' },
  { id: 'city_muzaffarpur', name: 'Muzaffarpur', type: 'CITY', lat: 26.1209, lng: 85.3647 },
  { id: 'stn_muzaffarpur', name: 'Muzaffarpur Junction', type: 'STATION', lat: 26.1209, lng: 85.3647, cityId: 'city_muzaffarpur' },
  { id: 'city_darbhanga', name: 'Darbhanga', type: 'CITY', lat: 26.1542, lng: 85.8918 },
  { id: 'apt_darbhanga', name: 'Darbhanga Airport', type: 'AIRPORT', lat: 26.1542, lng: 85.8918, cityId: 'city_darbhanga' },
  { id: 'stn_darbhanga', name: 'Darbhanga Junction', type: 'STATION', lat: 26.1542, lng: 85.8918, cityId: 'city_darbhanga', irctcCode: 'DBG' },
  { id: 'city_bareilly', name: 'Bareilly', type: 'CITY', lat: 28.367, lng: 79.4304 },
  { id: 'apt_bareilly', name: 'Bareilly Airport', type: 'AIRPORT', lat: 28.367, lng: 79.4304, cityId: 'city_bareilly' },
  { id: 'stn_bareilly', name: 'Bareilly Junction', type: 'STATION', lat: 28.367, lng: 79.4304, cityId: 'city_bareilly' },
  { id: 'city_aligarh', name: 'Aligarh', type: 'CITY', lat: 27.8974, lng: 78.088 },
  { id: 'stn_aligarh', name: 'Aligarh Junction', type: 'STATION', lat: 27.8974, lng: 78.088, cityId: 'city_aligarh' },
  { id: 'city_moradabad', name: 'Moradabad', type: 'CITY', lat: 28.8386, lng: 78.7733 },
  { id: 'stn_moradabad', name: 'Moradabad Junction', type: 'STATION', lat: 28.8386, lng: 78.7733, cityId: 'city_moradabad' },
  { id: 'city_saharanpur', name: 'Saharanpur', type: 'CITY', lat: 29.964, lng: 77.546 },
  { id: 'stn_saharanpur', name: 'Saharanpur Junction', type: 'STATION', lat: 29.964, lng: 77.546, cityId: 'city_saharanpur' },
  { id: 'city_jhansi', name: 'Jhansi', type: 'CITY', lat: 25.4484, lng: 78.5685 },
  { id: 'stn_jhansi', name: 'VGLB Jhansi Junction', type: 'STATION', lat: 25.4484, lng: 78.5685, cityId: 'city_jhansi' },
  { id: 'city_belagavi', name: 'Belagavi', type: 'CITY', lat: 15.8497, lng: 74.4977 },
  { id: 'apt_belagavi', name: 'Belagavi Airport', type: 'AIRPORT', lat: 15.8497, lng: 74.4977, cityId: 'city_belagavi' },
  { id: 'stn_belagavi', name: 'Belagavi Station', type: 'STATION', lat: 15.8497, lng: 74.4977, cityId: 'city_belagavi' },
  { id: 'city_hubballi', name: 'Hubballi', type: 'CITY', lat: 15.3647, lng: 75.124 },
  { id: 'apt_hubballi', name: 'Hubballi Airport', type: 'AIRPORT', lat: 15.3647, lng: 75.124, cityId: 'city_hubballi' },
  { id: 'stn_hubballi', name: 'Hubballi Junction', type: 'STATION', lat: 15.3647, lng: 75.124, cityId: 'city_hubballi' },
  { id: 'city_kolhapur', name: 'Kolhapur', type: 'CITY', lat: 16.705, lng: 74.2433 },
  { id: 'apt_kolhapur', name: 'Kolhapur Airport', type: 'AIRPORT', lat: 16.705, lng: 74.2433, cityId: 'city_kolhapur' },
  { id: 'stn_kolhapur', name: 'Chhatrapati Shahu Maharaj Terminus', type: 'STATION', lat: 16.705, lng: 74.2433, cityId: 'city_kolhapur' },
  { id: 'city_solapur', name: 'Solapur', type: 'CITY', lat: 17.6599, lng: 75.9064 },
  { id: 'apt_solapur', name: 'Solapur Airport', type: 'AIRPORT', lat: 17.6599, lng: 75.9064, cityId: 'city_solapur' },
  { id: 'stn_solapur', name: 'Solapur Station', type: 'STATION', lat: 17.6599, lng: 75.9064, cityId: 'city_solapur' },
  { id: 'city_amravati', name: 'Amravati', type: 'CITY', lat: 20.932, lng: 77.7523 },
  { id: 'stn_amravati', name: 'Amravati Station', type: 'STATION', lat: 20.932, lng: 77.7523, cityId: 'city_amravati' },
  { id: 'city_nanded', name: 'Nanded', type: 'CITY', lat: 19.1383, lng: 77.321 },
  { id: 'apt_nanded', name: 'Shri Guru Gobind Singh Ji Airport', type: 'AIRPORT', lat: 19.1383, lng: 77.321, cityId: 'city_nanded' },
  { id: 'stn_nanded', name: 'Hazur Sahib Nanded', type: 'STATION', lat: 19.1383, lng: 77.321, cityId: 'city_nanded' },
  { id: 'city_bikaner', name: 'Bikaner', type: 'CITY', lat: 28.0229, lng: 73.3119 },
  { id: 'apt_bikaner', name: 'Bikaner Airport', type: 'AIRPORT', lat: 28.0229, lng: 73.3119, cityId: 'city_bikaner' },
  { id: 'stn_bikaner', name: 'Bikaner Junction', type: 'STATION', lat: 28.0229, lng: 73.3119, cityId: 'city_bikaner' },
  { id: 'city_ajmer', name: 'Ajmer', type: 'CITY', lat: 26.4499, lng: 74.6399 },
  { id: 'apt_ajmer', name: 'Kishangarh Airport', type: 'AIRPORT', lat: 26.4499, lng: 74.6399, cityId: 'city_ajmer' },
  { id: 'stn_ajmer', name: 'Ajmer Junction', type: 'STATION', lat: 26.4499, lng: 74.6399, cityId: 'city_ajmer' },
  { id: 'city_kota', name: 'Kota', type: 'CITY', lat: 25.2138, lng: 75.8648 },
  { id: 'apt_kota', name: 'Kota Airport', type: 'AIRPORT', lat: 25.2138, lng: 75.8648, cityId: 'city_kota' },
  { id: 'stn_kota', name: 'Kota Junction', type: 'STATION', lat: 25.2138, lng: 75.8648, cityId: 'city_kota' },
  { id: 'city_bhavnagar', name: 'Bhavnagar', type: 'CITY', lat: 21.7645, lng: 72.1519 },
  { id: 'apt_bhavnagar', name: 'Bhavnagar Airport', type: 'AIRPORT', lat: 21.7645, lng: 72.1519, cityId: 'city_bhavnagar' },
  { id: 'stn_bhavnagar', name: 'Bhavnagar Terminus', type: 'STATION', lat: 21.7645, lng: 72.1519, cityId: 'city_bhavnagar' },
  { id: 'city_jamnagar', name: 'Jamnagar', type: 'CITY', lat: 22.4707, lng: 70.0577 },
  { id: 'apt_jamnagar', name: 'Jamnagar Airport', type: 'AIRPORT', lat: 22.4707, lng: 70.0577, cityId: 'city_jamnagar' },
  { id: 'stn_jamnagar', name: 'Jamnagar Station', type: 'STATION', lat: 22.4707, lng: 70.0577, cityId: 'city_jamnagar' },
  { id: 'city_surat', name: 'Surat', type: 'CITY', lat: 21.1702, lng: 72.8311 },
  { id: 'apt_surat', name: 'Surat Airport', type: 'AIRPORT', lat: 21.1702, lng: 72.8311, cityId: 'city_surat' },
  { id: 'stn_surat', name: 'Surat Station', type: 'STATION', lat: 21.1702, lng: 72.8311, cityId: 'city_surat' },
  { id: 'city_kurnool', name: 'Kurnool', type: 'CITY', lat: 15.8281, lng: 78.0373 },
  { id: 'apt_kurnool', name: 'Kurnool Airport', type: 'AIRPORT', lat: 15.8281, lng: 78.0373, cityId: 'city_kurnool' },
  { id: 'stn_kurnool', name: 'Kurnool City', type: 'STATION', lat: 15.8281, lng: 78.0373, cityId: 'city_kurnool' },
  { id: 'city_nellore', name: 'Nellore', type: 'CITY', lat: 14.4426, lng: 79.9865 },
  { id: 'stn_nellore', name: 'Nellore Station', type: 'STATION', lat: 14.4426, lng: 79.9865, cityId: 'city_nellore' },
  { id: 'city_salem', name: 'Salem', type: 'CITY', lat: 11.6643, lng: 78.146 },
  { id: 'apt_salem', name: 'Salem Airport', type: 'AIRPORT', lat: 11.6643, lng: 78.146, cityId: 'city_salem' },
  { id: 'stn_salem', name: 'Salem Junction', type: 'STATION', lat: 11.6643, lng: 78.146, cityId: 'city_salem' },
  { id: 'city_tirunelveli', name: 'Tirunelveli', type: 'CITY', lat: 8.7139, lng: 77.7567 },
  { id: 'apt_tirunelveli', name: 'Tuticorin Airport', type: 'AIRPORT', lat: 8.7139, lng: 77.7567, cityId: 'city_tirunelveli' },
  { id: 'stn_tirunelveli', name: 'Tirunelveli Junction', type: 'STATION', lat: 8.7139, lng: 77.7567, cityId: 'city_tirunelveli' },
  { id: 'city_vellore', name: 'Vellore', type: 'CITY', lat: 12.9165, lng: 79.1325 },
  { id: 'stn_vellore', name: 'Katpadi Junction', type: 'STATION', lat: 12.9165, lng: 79.1325, cityId: 'city_vellore' },
  { id: 'city_dhanbad', name: 'Dhanbad', type: 'CITY', lat: 23.7957, lng: 86.4304 },
  { id: 'stn_dhanbad', name: 'Dhanbad Junction', type: 'STATION', lat: 23.7957, lng: 86.4304, cityId: 'city_dhanbad' },
  { id: 'city_bokaro', name: 'Bokaro', type: 'CITY', lat: 23.6693, lng: 86.1511 },
  { id: 'stn_bokaro', name: 'Bokaro Steel City', type: 'STATION', lat: 23.6693, lng: 86.1511, cityId: 'city_bokaro' },
  { id: 'city_asansol', name: 'Asansol', type: 'CITY', lat: 23.6739, lng: 86.9524 },
  { id: 'apt_asansol', name: 'Kazi Nazrul Islam Airport', type: 'AIRPORT', lat: 23.6739, lng: 86.9524, cityId: 'city_asansol' },
  { id: 'stn_asansol', name: 'Asansol Junction', type: 'STATION', lat: 23.6739, lng: 86.9524, cityId: 'city_asansol' },
  { id: 'city_durgapur', name: 'Durgapur', type: 'CITY', lat: 23.5204, lng: 87.3119 },
  { id: 'apt_durgapur', name: 'Kazi Nazrul Islam Airport', type: 'AIRPORT', lat: 23.5204, lng: 87.3119, cityId: 'city_durgapur' },
  { id: 'stn_durgapur', name: 'Durgapur Station', type: 'STATION', lat: 23.5204, lng: 87.3119, cityId: 'city_durgapur' },
  { id: 'city_kharagpur', name: 'Kharagpur', type: 'CITY', lat: 22.3302, lng: 87.3237 },
  { id: 'stn_kharagpur', name: 'Kharagpur Junction', type: 'STATION', lat: 22.3302, lng: 87.3237, cityId: 'city_kharagpur' },
  { id: 'city_bilaspur', name: 'Bilaspur', type: 'CITY', lat: 22.0797, lng: 82.1409 },
  { id: 'apt_bilaspur', name: 'Bilasa Devi Kevat Airport', type: 'AIRPORT', lat: 22.0797, lng: 82.1409, cityId: 'city_bilaspur' },
  { id: 'stn_bilaspur', name: 'Bilaspur Junction', type: 'STATION', lat: 22.0797, lng: 82.1409, cityId: 'city_bilaspur' },
  { id: 'city_durg', name: 'Durg', type: 'CITY', lat: 21.1938, lng: 81.2849 },
  { id: 'stn_durg', name: 'Durg Junction', type: 'STATION', lat: 21.1938, lng: 81.2849, cityId: 'city_durg' },
  { id: 'city_kollam', name: 'Kollam', type: 'CITY', lat: 8.8932, lng: 76.6141 },
  { id: 'stn_kollam', name: 'Kollam Junction', type: 'STATION', lat: 8.8932, lng: 76.6141, cityId: 'city_kollam' },
  { id: 'city_thrissur', name: 'Thrissur', type: 'CITY', lat: 10.5276, lng: 76.2144 },
  { id: 'stn_thrissur', name: 'Thrissur Station', type: 'STATION', lat: 10.5276, lng: 76.2144, cityId: 'city_thrissur' },
  { id: 'city_alappuzha', name: 'Alappuzha', type: 'CITY', lat: 9.4981, lng: 76.3388 },
  { id: 'stn_alappuzha', name: 'Alappuzha Station', type: 'STATION', lat: 9.4981, lng: 76.3388, cityId: 'city_alappuzha' },
  { id: 'city_kannur', name: 'Kannur', type: 'CITY', lat: 11.8745, lng: 75.3704 },
  { id: 'apt_kannur', name: 'Kannur Int. Airport', type: 'AIRPORT', lat: 11.8745, lng: 75.3704, cityId: 'city_kannur' },
  { id: 'stn_kannur', name: 'Kannur Station', type: 'STATION', lat: 11.8745, lng: 75.3704, cityId: 'city_kannur' },
  { id: 'city_guntur', name: 'Guntur', type: 'CITY', lat: 16.3067, lng: 80.4365 },
  { id: 'stn_guntur', name: 'Guntur Junction', type: 'STATION', lat: 16.3067, lng: 80.4365, cityId: 'city_guntur' },
  { id: 'city_warangal', name: 'Warangal', type: 'CITY', lat: 17.9811, lng: 79.5318 },
  { id: 'stn_warangal', name: 'Warangal Station', type: 'STATION', lat: 17.9811, lng: 79.5318, cityId: 'city_warangal' },
  { id: 'city_nizamabad', name: 'Nizamabad', type: 'CITY', lat: 18.6725, lng: 78.0941 },
  { id: 'stn_nizamabad', name: 'Nizamabad Junction', type: 'STATION', lat: 18.6725, lng: 78.0941, cityId: 'city_nizamabad' },
  { id: 'city_karnal', name: 'Karnal', type: 'CITY', lat: 29.6857, lng: 76.9905 },
  { id: 'stn_karnal', name: 'Karnal Station', type: 'STATION', lat: 29.6857, lng: 76.9905, cityId: 'city_karnal' },
  { id: 'city_panipat', name: 'Panipat', type: 'CITY', lat: 29.3909, lng: 76.9635 },
  { id: 'stn_panipat', name: 'Panipat Junction', type: 'STATION', lat: 29.3909, lng: 76.9635, cityId: 'city_panipat' },
  { id: 'city_rohtak', name: 'Rohtak', type: 'CITY', lat: 28.8955, lng: 76.5892 },
  { id: 'stn_rohtak', name: 'Rohtak Junction', type: 'STATION', lat: 28.8955, lng: 76.5892, cityId: 'city_rohtak' },
  { id: 'city_hisar', name: 'Hisar', type: 'CITY', lat: 29.1492, lng: 75.7217 },
  { id: 'apt_hisar', name: 'Hisar Airport', type: 'AIRPORT', lat: 29.1492, lng: 75.7217, cityId: 'city_hisar' },
  { id: 'stn_hisar', name: 'Hisar Junction', type: 'STATION', lat: 29.1492, lng: 75.7217, cityId: 'city_hisar' },
  { id: 'city_bhatinda', name: 'Bhatinda', type: 'CITY', lat: 30.211, lng: 74.9455 },
  { id: 'apt_bhatinda', name: 'Bathinda Airport', type: 'AIRPORT', lat: 30.211, lng: 74.9455, cityId: 'city_bhatinda' },
  { id: 'stn_bhatinda', name: 'Bathinda Junction', type: 'STATION', lat: 30.211, lng: 74.9455, cityId: 'city_bhatinda' },
  { id: 'city_pathankot', name: 'Pathankot', type: 'CITY', lat: 32.2643, lng: 75.6469 },
  { id: 'apt_pathankot', name: 'Pathankot Airport', type: 'AIRPORT', lat: 32.2643, lng: 75.6469, cityId: 'city_pathankot' },
  { id: 'stn_pathankot', name: 'Pathankot Junction', type: 'STATION', lat: 32.2643, lng: 75.6469, cityId: 'city_pathankot' },
  { id: 'city_hoshiarpur', name: 'Hoshiarpur', type: 'CITY', lat: 31.5274, lng: 75.9123 },
  { id: 'stn_hoshiarpur', name: 'Hoshiarpur Station', type: 'STATION', lat: 31.5274, lng: 75.9123, cityId: 'city_hoshiarpur' },
  { id: 'city_imphal', name: 'Imphal', type: 'CITY', lat: 24.817, lng: 93.9368 },
  { id: 'apt_imphal', name: 'Bir Tikendrajit Int. Airport', type: 'AIRPORT', lat: 24.817, lng: 93.9368, cityId: 'city_imphal' },
  { id: 'city_aizawl', name: 'Aizawl', type: 'CITY', lat: 23.7271, lng: 92.7176 },
  { id: 'apt_aizawl', name: 'Lengpui Airport', type: 'AIRPORT', lat: 23.7271, lng: 92.7176, cityId: 'city_aizawl' },
  { id: 'city_kohima', name: 'Kohima', type: 'CITY', lat: 25.6751, lng: 94.1086 },
  { id: 'city_itanagar', name: 'Itanagar', type: 'CITY', lat: 27.0844, lng: 93.6053 },
  { id: 'apt_itanagar', name: 'Donyi Polo Airport', type: 'AIRPORT', lat: 27.0844, lng: 93.6053, cityId: 'city_itanagar' },
  { id: 'stn_itanagar', name: 'Naharlagun Station', type: 'STATION', lat: 27.0844, lng: 93.6053, cityId: 'city_itanagar' },
  { id: 'city_gangtok', name: 'Gangtok', type: 'CITY', lat: 27.3389, lng: 88.6065 },
  { id: 'apt_gangtok', name: 'Pakyong Airport', type: 'AIRPORT', lat: 27.3389, lng: 88.6065, cityId: 'city_gangtok' },
];

export const getGeoNode = (query: string): GeoNode | undefined => {
  const search = query.toLowerCase();
  return GEO_DB.find(node => node.name.toLowerCase().includes(search) || node.id.includes(search));
};

const FAMOUS_CITIES = new Set([
  'city_agartala', 'city_agra', 'city_ahmedabad', 'city_aizawl', 'city_ajmer',
  'city_alappuzha', 'city_aligarh', 'city_amravati', 'city_amritsar', 'city_asansol',
  'city_aurangabad', 'city_bangalore', 'city_bareilly', 'city_belagavi', 'city_bhagalpur',
  'city_bhatinda', 'city_bhavnagar', 'city_bhopal', 'city_bhubaneswar', 'city_bikaner',
  'city_bilaspur', 'city_bokaro', 'city_chandigarh', 'city_chennai', 'city_coimbatore',
  'city_darbhanga', 'city_dehradun', 'city_delhi', 'city_dhanbad', 'city_dibrugarh',
  'city_durg', 'city_durgapur', 'city_gangtok', 'city_gaya', 'city_goa', 'city_gorakhpur',
  'city_guntur', 'city_guwahati', 'city_gwalior', 'city_hisar', 'city_hoshiarpur',
  'city_hubballi', 'city_hyderabad', 'city_imphal', 'city_indore', 'city_itanagar',
  'city_jabalpur', 'city_jaipur', 'city_jammu', 'city_jamnagar', 'city_jamshedpur',
  'city_jhansi', 'city_jodhpur', 'city_kannur', 'city_kanpur', 'city_karnal',
  'city_kharagpur', 'city_kochi', 'city_kohima', 'city_kolhapur', 'city_kolkata',
  'city_kollam', 'city_kota', 'city_kozhikode', 'city_kurnool', 'city_leh', 'city_lucknow',
  'city_ludhiana', 'city_madurai', 'city_mangalore', 'city_moradabad', 'city_mumbai',
  'city_muzaffarpur', 'city_mysore', 'city_nagpur', 'city_nanded', 'city_nashik',
  'city_nellore', 'city_nizamabad', 'city_panipat', 'city_pathankot', 'city_patiala',
  'city_patna', 'city_prayagraj', 'city_pune', 'city_raipur', 'city_rajkot', 'city_ranchi',
  'city_rohtak', 'city_rourkela', 'city_saharanpur', 'city_salem', 'city_shillong',
  'city_silchar', 'city_siliguri', 'city_solapur', 'city_srinagar', 'city_surat',
  'city_thiruvananthapuram', 'city_thrissur', 'city_tiruchirappalli', 'city_tirunelveli',
  'city_tirupati', 'city_udaipur', 'city_ujjain', 'city_vadodara', 'city_varanasi',
  'city_vellore', 'city_vijayawada', 'city_visakhapatnam', 'city_warangal'
]);

export const findNearbyAirports = (lat: number, lng: number, maxRadiusKm: number = 500): GeoNode[] => {
  const airportsWithDist = GEO_DB
    .filter(node => node.type === 'AIRPORT' && node.cityId && FAMOUS_CITIES.has(node.cityId))
    .map(apt => {
      const coords = getNodeCoords(apt);
      const dist = Haversine.getDistance(lat, lng, coords.lat, coords.lng);
      return { apt, dist };
    })
    .filter(item => item.dist <= maxRadiusKm);

  // Sort by closest first and take the top 6 to avoid blasting the API with 15 concurrent requests
  airportsWithDist.sort((a, b) => a.dist - b.dist);

  return airportsWithDist.slice(0, 8).map(item => item.apt);
};
